### ISSUE TITLE
Unable to install in IDE

### ISSUE THREAD

**Issue by jamiehoward430** [chrishamm/ArduinoDuet#2]
Hi,

I am trying to install this into my IDE but I keep getting the below error,

`http://chrishamm.reprapfirmware.org/package_reprap_index.json file signature verification failed. File ignored`.

I have tried the usual of uninstalling/reinstalling and deleting folders in appdata but it still does it,
any other suggestions please?

**Comment by chrishamm** [comment]
Hi, I could confirm this issue. Looks like Arduino no longer accepts an empty file for the JSON sig, so I had to move the whole package to a different location. Please change the link to

https://chrishamm.io/arduino/package_reprap_index.json

and try to install it again. I just updated the ArduinoDuet+RepRapFirmware repostories by merging in dc42's latest improvements but be aware that this will be the last or one of the last versions that I will publish on my own GitHub page. In the future I will only contribute directly to dc42's RRF/CoreNG repositories.
